apiVersion: apps/v1
kind: Deployment

metadata:
  name: tetris

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tetris

  template:
    metadata:
      labels:
        app: tetris

    spec:

      containers:
      - name: tetris

        image: agdevopsacr2026.azurecr.io/tetris:810d14807e6b226e16306fc4a3f62151579aecfb

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

