apiVersion: apps/v1
kind: Deployment

metadata:
  name: tetris

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tetris
      version: v1

  template:
    metadata:
      labels:
        app: tetris
        version: v1

    spec:

      containers:
      - name: tetris

        image: agdevopsacr2026.azurecr.io/tetris:50f91fc0762bcb9950b07e7e0658aceb6ba738a7

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

