apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: idp-ingress

spec:
  ingressClassName: nginx

  rules:
  - http:
      paths:
      - path: /tic-tac-toe
        pathType: Prefix
        backend:
          service:
            name: tic-tac-toe
            port:
              number: 80

      - path: /tetris
        pathType: Prefix
        backend:
          service:
            name: tetris
            port:
              number: 80