apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 04fc74f0-95c5-4c3e-b941-58b964b6ee6f

    keyvaultName: "agdevopskv2026"
    tenantId: "494d8408-c1d7-4771-8716-be4275838741"

    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
