apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 10c20851-b7de-4d9a-ae33-7568bffb4361

    keyvaultName: "agdevopskv2026"
    tenantId: "494d8408-c1d7-4771-8716-be4275838741"

    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
