apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 5b2b5671-dba4-4f1c-be8a-f768db9d22eb

    keyvaultName: "agdevopskv2026"
    tenantId: "494d8408-c1d7-4771-8716-be4275838741"

    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
