apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "0e3f3ff1-d3b2-46e0-b2dd-97c1fd058346"

    keyvaultName: "agdevopskv2026"
    tenantId: "494d8408-c1d7-4771-8716-be4275838741"

    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
