name: Azure Running Resources

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-devops-demo

  TFSTATE_RG: rg-tf-backend
  TFSTATE_STORAGE: agtfstate2026xyz
  TFSTATE_CONTAINER: tfstate

jobs:

  audit:

    runs-on: ubuntu-latest

    steps:

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Running Resources
        run: |

          echo ""
          echo "========================================================"
          echo "            AZURE RUNNING RESOURCES"
          echo "========================================================"

          echo ""
          echo "Subscription"
          echo "--------------------------------------------------------"

          echo ""
          echo "Infrastructure"
          echo "--------------------------------------------------------"

          RG_EXISTS=$(az group exists --name $RESOURCE_GROUP)

          if [ "$RG_EXISTS" = "true" ]; then;

            echo ""
            echo "✅ Resource Group : $RESOURCE_GROUP"

            echo ""
            echo "AKS Cluster"
            az aks list \
              --resource-group $RESOURCE_GROUP \
              --query "[].{Name:name,Location:location,Version:kubernetesVersion}" \
              -o table

            echo ""
            echo "Azure Container Registry"
            az acr list \
              --resource-group $RESOURCE_GROUP \
              --query "[].{Name:name,SKU:sku.name}" \
              -o table

            echo ""
            echo "Key Vault"
            az keyvault list \
              --resource-group $RESOURCE_GROUP \
              --query "[].{Name:name}" \
              -o table

          else

            echo ""
            echo "❌ Resource Group : Not Found"
            echo "❌ AKS Cluster    : Not Found"
            echo "❌ ACR            : Not Found"
            echo "❌ Key Vault      : Not Found"

          fi