name: Scale Application

on:
  workflow_dispatch:
    inputs:
      application_name:
        description: "Application Name"
        required: true
        default: "tic-tac-toe"
        type: choice
        options:
          - tic-tac-toe
          - tetris

      replicas:
        description: "Number of Replicas"
        required: true
        default: 2
        type: number

jobs:

  scale:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify AKS Exists
        run: |
          echo "Checking AKS Cluster..."

          az aks show \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER }} \
            --output table

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER }} \
            --overwrite-existing

      - name: Scale Deployment
        run: |
          kubectl scale deployment \
          ${{ github.event.inputs.application_name }} \
          --replicas=${{ github.event.inputs.replicas }}

      - name: Verify Scaling
        run: |
          kubectl get deployment ${{ github.event.inputs.application_name }}

          kubectl get pods \
            -l app=${{ github.event.inputs.application_name }} \
            -o wide

      - name: Scale Summary
        run: |

          echo ""
          echo "========================================================"
          echo "APPLICATION SCALED SUCCESSFULLY"
          echo "========================================================"

          echo ""
          echo "Application : ${{ github.event.inputs.application_name }}"
          echo "Replicas    : ${{ github.event.inputs.replicas }}"

          echo ""
          kubectl get deployment ${{ github.event.inputs.application_name }}

          echo ""
          echo "========================================================"